### ISSUE TITLE
Angel Ring not craftable

### ISSUE THREAD

**Issue by Yamza** [AllTheMods/ATM3-Remix#125]
When done correctly, the two lassos are created with extra NBT data that the recipe is not ignoring. 

What is actually able to be made by the player: https://i.imgur.com/eLKJjs6.png
What the recipe is expecting: https://i.imgur.com/IgercXG.png

Only workaround is cheating to bypass it.

**Comment by Spyboticsguy** [comment]
Replicated on version 1.0.2. Looking into potential causes. It seems like XU2 doesn't do anything special on its own to support the NBT it uses in crafting.

Manually spawning the lassos with only the required NBT data works.

The only difference is that XU2 sets No_Place as a boolean instead of directly setting it to 1 as a byte; there should be no technical difference between the two but I am trying that now.

**Comment by Yamza** [comment]
It's a crafttweaker bug, should be fixed next update.
