### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by MacWhinny** [AllTheMods/ATM3-Remix#146]
I have a few suggestions but not all have mods to show for them though. 

One was an auto ranking mod, to help manage servers and rank players up for time played

The second was more server commands, FTBU commands suck and haven't been updated in years Lat said. So having more of an essentials styled mod with a massive amount of commands for servers would be great. 

and the third being an Economy mod. https://www.curseforge.com/minecraft/mc-mods/economy-inc

Last one being a way to ban terms, it being from interaction to just placement and lastly from being crafted. I know you've said nothing should need banning but i think some server owners may want to stop player from either interacting/placing/crafting some items.
https://minecraft.curseforge.com/projects/item-blacklist or something like it (Updated 2 days ago)

These all depend on if there are any mods like these out there for the ones i have not provided. 
Would just be nice to have some more server related tools to help manage my server. SO that i can make it much better.

**Comment by FallenEagle1** [comment]
Couple of things here. First, there is a suggestions issue open already, it helps keep things consolidated some. The blacklist isn't too bad of an idea, will look into it some to help out server owners. As for ftbu, it had an update 2 hours ago, and 13 updates since the beginning of the year, so not sure where your info is from. As for the economy mod, neutral on it at the moment. Partly because I don't know much on it besides what is on the curse page for the mod.

I would put these on the suggestions issue though, so they get looked into.

**Comment by MacWhinny** [comment]
Sorry i mean with FTBU is that Lat said he hasn't updated the commands in years. Ie not added any. 

Sorry my bad

And thanks you, that would be great and good to know that an economy mod is being looked into 

and yay a ban item mod :)

**Comment by MacWhinny** [comment]
Any chance you have the link to the page where you added my ideas to the ones that have been made? SO i can take a look myself please

**Comment by FallenEagle1** [comment]
#10
