### ISSUE TITLE
Diamond duplication

### ISSUE THREAD

**Issue by Minyguy** [AllTheMods/ATM3-Remix#15]
It's possible to duplicate diamonds using astral sorcery and mekanism.

## Expected Behavior
You shouldn't be able to indefinetly reprocess diamonds into more diamonds. 

## Current Behavior
You can make infinite diamonds using rf and some simple machinery from mekanism and an astral sorcery infuser.
Although, it costs energy and liquid starlight.

## Possible Solution
Increase the recipie for diamond ore to 4x diamonds

## Steps to Reproduce
1. Take 3 diamonds
2. Crush them in a "Crusher" from "Mekanism" 
3. turn it into diamond ore with the "Combiner" from "Mekanism"
4. infuse them with the infuser from astral sorcery (You get 4 diamonds back)

**Comment by NebulouStorm** [comment]
Doesn't the infuser require liquid starlight, which is a technically non-renewable resource, because rock crystal and/or aquamarine reproduction is not possible?
Theoretically, this is also possible using some very "end game" portions of astral sorcery. It has a system that allows you to create enchantments of levels normally not possible (like protection 6 or 7, or fortune 4-5, or higher). By enchanting a pickaxe with a fortune level higher than 3, you should have a net average of higher than 3, thus making diamond duplication possible with that as well.
However, it is worth noting that, in my opinion, if you have managed to get that far into the mod, you either have a quarry anyway, or have another method of obtaining infinite resources that likely involves MUCH less effort than automating the entirety of that system.
