### ISSUE TITLE
Seedless Beetroot

### ISSUE THREAD

**Issue by SneakyDevil** [AllTheMods/ATM3-Remix#158]
Beetroot seeds can only be acquired via botania carrot transfiguration

## Expected Behavior
I'm not sure, its one of the four basic crops, I'm assuming it shouldn't do that?

## Current Behavior
Seeds for beetroot don't exist via normal crafting

**Comment by FallenEagle1** [comment]
None of the mods add anything for beetroot, so it is just default vanilla interaction for it. You can find beetroot also in villages in the farm patches. There's no crafting recipe for seeds either from wheat, but this normally isn't an issue since seeds can be found by breaking grass, it's the vanilla default. Will leave this open for now.
