### ISSUE TITLE
Moss/Polished Stone Recipes Conflict

### ISSUE THREAD

**Issue by SneakyDevil** [AllTheMods/ATM3-Remix#162]
As it says on the tin, 2x2 mossy bricks can make Polished Stone from extra utils or it can make TC Moss Balls. Polished Stone takes priority leaving no means of making moss balls.

**Comment by SneakyDevil** [comment]
Update: This only happens to specifically the Mossy Stone Brick recipe, Moss balls can still be obtained from Mossy Cobblestone.

**Comment by DoctorNefario** [comment]
The polished stone recipe normally creates 4 polished stone, but because of this change it now creates 1.

In my opinion, this change should be undone, or at least reduced. The main issue is that you are unable to craft moss balls with mossy bricks, you can still use all the other mossy blocks. Perhaps just change the moss ball recipe to exclude bricks so there's no confusion.
