### ISSUE TITLE
"server lag" but for only one player at a time, occasional disconnects

### ISSUE THREAD

**Issue by DerpityDoo** [AllTheMods/ATM3-Remix#183]
Currently running a server for a few friends on second computer. We all experience occasional lag spikes that rubberband us around, but it's never experienced by more than one person at a time. I am connected to the server via an internal network IP address so I know it isn't the internet connection, and everything is running on ethernet. When the lag spike lasts long enough, the player gets disconnected, and I get a big red disconnect message in console.

Disconnect message: https://pastebin.com/fPuhC6Z7
Latest.logV2: https://gist.github.com/DerpityDoo/fba64982d19c1eeedcbb673c1832a89f
Maybe the problem is obvious but I tried to glean anything from the disconnect message and the log but I am just not familiar with the problem I guess. Thanks in advance for any help you provide.

**Comment by DerpityDoo** [comment]
I should mention that the only things I have modified about the server were the Java args, but I changed them in an attempt to fix the problem, but the problem remained the same.

**Comment by Darkere** [comment]
The latest.log is just the server starting without anyone connecting.

**Comment by DerpityDoo** [comment]
Oh whoops, I forgot that when I went to copy the disconnect message the server ended up restarting. I will have to wait until I get disconnected again to post a better latest.log

**Comment by DerpityDoo** [comment]
Ok I edited my original post with the new lastest.log

**Comment by Darkere** [comment]
This might be entirely unrelated but:
` logs\blooddebug.log -> logs\blooddebug_old\blooddebug2019-05-13-08-12-35.log: The process cannot access the file because it is being used by another process.`

Something is interfering with things in that directory. This can cause every issue imaginable. Moving the server from the desktop to like C:/minecraft or something is the easiest fix. 

The error might be on the Client can you get the log from there too?.

You are using Sponge. We recommend against that as Sponge is not quite keeping up with current updates and generally breaks a lot of other mods.

**Comment by DerpityDoo** [comment]
Wait I'm using sponge? I have "USE_SPONGE=0" in the settings.cfg, how is that possible?

**Comment by Darkere** [comment]
Uh, nvm it's saying spongepowered quite often so I assumed. Probably some mod using their stuff.

**Comment by DerpityDoo** [comment]
Moving the servers folder to Roaming didn't seem to change anything. I also whitelisted the folder in my antivirus and double checked that windows defender is disabled. I no longer see any files being tied up by another process, but the lag is still present.

**Comment by Darkere** [comment]
Like I said probably unrelated. Can still lead to crashing so good that its fixed.  

If only one player is affected then its either his game or the place where he is playing.  Ofc connection issues are also always a possibility.

The log of the client should have info on why the player was disconnected.

**Comment by SpeedSlider** [comment]
A good thing to look for in the server console is server error about unable to keep up. That will generally indicate if too much is being loaded at any given time. An example would be a player loading chunks while traveling quickly (e.g. flight or boat travel in new chunks). This problem is difficult to address for any server. Rubber banding is typically an indication that client and server are not in sync usually due to large amounts of data being processed by server, client, or both. If you don't get the unable to keep up message in the console then it is likely a client issue or connection issue. In servers using the "tab" key will give you a general idea of connection quality of individual players which may help determine the issue as well. Use of our Help Desk in discord may help us help you faster.
