### ISSUE TITLE
Add Empowerer Recipes to Draconic Evolution Fusion Crafting

### ISSUE THREAD

**Issue by fabrossmann** [AllTheMods/ATM3-Remix#184]
## Detailed Description
You should be able, to make the Recipes, that the Empowerer is able to do with DE Fusion Crafting like in the Modpack Enigmatica2. It is basically the same thing and it would be more comfortable to use in auto-crafting, since you can put everything on one machine.

**Comment by FallenEagle1** [comment]
Will see what others think of this, but I'm leaning towards not really needed. The only item really that you need any large amount of is the atm growth essence, and it already has a fusion crafting recipe. Otherwise, adding all of the recipes just for the sake of one less thing to automate doesn't seem necessary. It's fairly easy to automate already, just place all items in a single chest, and filter out based on where items need to go. Can argue about pushing too much into a chest at once, but ae2 has blocking mode that can be used for this.
