### ISSUE TITLE
MAJOR Memory Leak (allocated 6 GB and it took 9!)

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [AllTheMods/ATM3-Remix#190]
## Expected Behavior
Modpack should run just fine, staying under the allocated memory. I have ran it perfectly fine once before and after that is when this started happening.

## Current Behavior
It's currently eating up all my allocated ram, which is a 6 GB allocation, and more. It's going up to 9 GB of ram usage.

I've tried many launchers, JVM arguments, reinstalling both Java and the modpack and Minecraft itself, can't find anything on the internet that works to fix this.

## Steps to Reproduce
I made a habit of using Task Manager to close my game instead of doing it the normal way, other then that I have no idea what could have caused it.

## Log
[https://gist.githubusercontent.com/AdovinOFFICIAL/af369ec54edfe580b84446cd6eaf4641/raw/e0c82f5163622f6e18efd2cc96d8a7f309997149/gistfile1.txt](https://gist.githubusercontent.com/AdovinOFFICIAL/af369ec54edfe580b84446cd6eaf4641/raw/e0c82f5163622f6e18efd2cc96d8a7f309997149/gistfile1.txt)
Although the game didn't crash on its own (sometimes it does) I instead force closed the game with Task Manager because it was starting to climb rapidly in memory and I did not want to have my computer crash. I grabbed the log that MultiMC gave me after, though.

## Specs
Intel i7-7700k (4.20 GHz)
16 GB of RAM 2133 Mhz
NVIDIA GTX 1080 Ti

**Comment by Yamza** [comment]
Modpack has never stayed under the allocated ram. This is normal behavior. Java will take more beyond what minecraft is allocated to, and generally exceeds 10GB while loading.

**Comment by FallenEagle1** [comment]
This technically isn't a leak, its more of how java works. I'll try explaining it the way it was told to me, see if it helps. First thing, a leak is more of the when something in memory is allocated, but is then not properly released. As things are allocated then cleaned up by garbage collection, the things not released are not cleaned up, so the amount of memory grows over time.
This isn't the case for what you are seeing. I'll say up front, I don't know what all uses the memory, but what some of it breaks down to is: The amount you allocate is what minecraft itself is what it will allocate and eventually use. On top of that, there is some background process's that java runs, for things like log making, and making crash reports when needed. Ideally the amount you allocate is what both of these should take total, but that isn't how minecraft/java is programmed (not sure which is the cause for this in this case) 
So minecraft uses what you give it, then there is some put on top for the background stuff associated with it. Currently, I don't know of any way to change this behavior, or to minimize the required amounts needed for the background. It just comes across as what tends to be needed. Since it is a bigger pack, the background stuff tends to be larger.

**Comment by AdovinOFFICIAL** [comment]
> This technically isn't a leak, its more of how java works. I'll try explaining it the way it was told to me, see if it helps. First thing, a leak is more of the when something in memory is allocated, but is then not properly released. As things are allocated then cleaned up by garbage collection, the things not released are not cleaned up, so the amount of memory grows over time.
> This isn't the case for what you are seeing. I'll say up front, I don't know what all uses the memory, but what some of it breaks down to is: The amount you allocate is what minecraft itself is what it will allocate and eventually use. On top of that, there is some background process's that java runs, for things like log making, and making crash reports when needed. Ideally the amount you allocate is what both of these should take total, but that isn't how minecraft/java is programmed (not sure which is the cause for this in this case)
> So minecraft uses what you give it, then there is some put on top for the background stuff associated with it. Currently, I don't know of any way to change this behavior, or to minimize the required amounts needed for the background. It just comes across as what tends to be needed. Since it is a bigger pack, the background stuff tends to be larger.

if you dont mind, how much RAM usage do you get when playing this modpack?

**Comment by Yamza** [comment]
Typically it goes to 10.5GB while loading and for a while after. Around 30 minutes to an hour roughly it drops down to 6GB. I would suggest following this guide: https://www.reddit.com/r/allthemods/comments/968r4k/how_to_fix_modpack_wont_load_fps/

**Comment by FallenEagle1** [comment]
For my computer I dont tend to have it run quite as high as what yamza is talking about, it does tend to run 1.5 or so higher than set at, and then drop after a while. It varies some, depending on what version of the modpack is being run as well.
