### ISSUE TITLE
Suggestion: Refined Storage Creative Recipes.

### ISSUE THREAD

**Issue by KaneHart** [AllTheMods/ATM3-Remix#46]
Would be nice to see recipes for the following items:
Creative Portable Grid
Creative Wireless Grid
Creative Wireless Crafting Grid
Creative Wireless Fluid Grid
Creative Wireless Crafting Monitor

**Comment by FallenEagle1** [comment]
It seems with these items that the only thing that creative grants for these items is that they don't require rf to run. In order to get these, if the atm star is what is needed to get them, I feel like rf is not an issue, especially since a couple of different capacitors are part of the crafting recipes needed for this.
