### ISSUE TITLE
Crash on world start.

### ISSUE THREAD

**Issue by ConnCraft** [AllTheMods/ATM3-Remix#73]
Version: ATM3 Remix 0.1.2
https://pastebin.com/WqPM6jsb
Doesn't generate a crash log, so I pasted some of the log. Full log won't fit into pastebin.

**Comment by Yoosk** [comment]
Since you have github account, please use https://gist.github.com and paste full log there, crash seems related to corrupted xml from advanced rocketry, but i need full log to confirm it.

**Comment by FallenEagle1** [comment]
Looks like it is the issue of the planetsDef.xml file not able to be read. One of two things can be done. First thing I would try is replace the planetsDef.xml file with one that doesn't have issues, such as this one in the zipped folder.
[planetDefs.zip](https://github.com/AllTheMods/ATM3-Remix/files/2511695/planetDefs.zip)
Otherwise, if that doesn't work, a world backup should take care of it.

**Comment by ConnCraft** [comment]
planetsDef.xml appeared to be empty. Replacing it with one from a backup
fixed the issue. Thank you.
